name: Test Package

on:
  workflow_dispatch:

jobs:
  macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main      
      - name: Build
        run: swift build
      - name: Test
        run: swift test

  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: swift build
      - name: Test
        run: swift test

  Windows:
    runs-on: windows-latest
    steps:
      - name: Setup Swift
        uses: compnerd/gha-setup-swift@main
        with:
          swift-version: swift-6.3-release 
          swift-build: 6.3-RELEASE
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: swift build
      - name: Test
        run: swift test

  Android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test
        uses: skiptools/swift-android-action@main

  Apple_Matrix:
    strategy:
      matrix:
        include:
         - platform: iOS
           device: iPhone 17

         - platform: watchOS
           device: Apple Watch SE 3

         - platform: visionOS
           device: Apple Vision Pro

         - platform: tvOS
           device: Apple TV 4K
          
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test
        run: xcodebuild test -destination "platform=${{ matrix.platform }} Simulator,name=${{ matrix.device }}" -scheme "$(xcodebuild -list -json | jq -r '.workspace.schemes[-1]')"

  WASI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test
        uses: brightdigit/swift-build@main
        with:
          type: wasm
          platform: wasm
