name: Test Package

on:
  workflow_dispatch:

jobs:
  macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main      
      - name: Build
        run: swift build
      - name: Test
        run: swift test

  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: swift build
      - name: Test
        run: swift test

  Windows:
    runs-on: windows-latest
    steps:
      - name: Setup Swift
        uses: compnerd/gha-setup-swift@main
        with:
          swift-version: swift-6.3-release 
          swift-build: 6.3-RELEASE
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: swift build
      - name: Test
        run: swift test

  Android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test
        uses: skiptools/swift-android-action@main

  Apple: 
    strategy: 
      matrix: 
        include: 
          - platform: iOS
            device: iPhone 17
            os: 26.2
          - platform: watchOS 
            device: Apple Watch Series 11 (46mm) 
            os: 26.2
          - platform: visionOS 
            device: Apple Vision Pro 
            os: 26.2
          - platform: tvOS 
            device: Apple TV 
            os: 26.2
            
    runs-on: macos-latest 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v6 
      - name: Test 
        run: xcodebuild test -destination "platform=${{ matrix.platform }} Simulator,name=${{ matrix.device }},OS=${{ matrix.os }}" -scheme "$(xcodebuild -list -json | jq -r '.workspace.schemes[-1]')"

  WASM:
    runs-on: macos-latest
    steps:
      - run: swift sdk install https://download.swift.org/swift-6.3-release/wasm-sdk/swift-6.3-RELEASE/swift-6.3-RELEASE_wasm.artifactbundle.tar.gz --checksum 9fa4016ee632c7e9e906608ec3b55cf13dfc4dff44e47574c5af58064dc33fd9
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        run: swift build --swift-sdk swift-6.3-RELEASE_wasm
