name: Test Package

on:
  workflow_dispatch:

jobs:
  macOS:
    runs-on: macos-latest
    steps:
      - name: Setup Swift
        uses: swift-actions/setup-swift@main
        with:
          swift-version: 6.3
      - name: Checkout
        uses: actions/checkout@main      
      - name: Build
        run: swift build
      - name: Test
        run: swift test

  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Swift
        uses: swift-actions/setup-swift@main
        with:
          swift-version: 6.3
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: swift build
      - name: Test
        run: swift test

  Windows:
    runs-on: windows-latest
    steps:
      - name: Setup Swift
        uses: compnerd/gha-setup-swift@main
        with:
          swift-version: swift-6.3-release 
          swift-build: 6.3-RELEASE
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: swift build
      - name: Test
        run: swift test

  Android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test
        uses: skiptools/swift-android-action@main

  iOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test
        uses: brightdigit/swift-build@main
        with:
          type: ios
          deviceName: iPhone 17
          osVersion: latest
          scheme: SpeechKit
          swift-version: 6.3

  watchOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test
        uses: brightdigit/swift-build@main
        with:
          type: watchos

  visionOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test
        uses: brightdigit/swift-build@main
        with:
          type: visionos

  tvOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test
        uses: brightdigit/swift-build@main
        with:
          type: tvos

  WASI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test
        uses: brightdigit/swift-build@main
        with:
          type: wasm
          platform: wasm
